### PR TITLE
Add notifications about new question and answered to own question

### PR DESCRIPTION
**Pull request by yurabakhtin**
https://github.com/humhub/questions/issues/8

### CODE REVIEW

**Comment by luke-** [comment]
@yurabakhtin Can you please extract message texts for Semir to review?

**Comment by yurabakhtin** [comment]
@Semir1212 Please review the messages:

- `Q&A`
- `Receive Notifications when a question is created or answered to own questions.`

notif-setting

- `New question "{questionTitle}"`
- `{displayName} has created the Question "{contentTitle}" in Space {spaceName}.`
- `{displayName} has created the Question "{contentTitle}".`

email-question

- `Answered to your question "{questionTitle}"`
- `{displayName} has answered to your Question "{contentTitle}" in Space {spaceName}.`
- `{displayName} has answered to your Question "{contentTitle}".`

email-answered

**Comment by Semir1212** [comment]
@yurabakhtin 


> * `Receive Notifications when a question is created or answered to own questions.` --> Receive notifications when a Question is created or your questions are answered.

> * `New question "{questionTitle}"` --> New Question "{questionTitle}"`

> * `Answered to your question "{questionTitle}"`--> `New answer to your Question "{questionTitle}"`
> {displayName} has answered to your Question "{contentTitle}" in Space {spaceName}. --> {displayName} has answered your Question "{contentTitle}" in Space {spaceName}.
> {displayName} has answered to your Question "{contentTitle}". --> {displayName} has answered your Question "{contentTitle}".

**Comment by yurabakhtin** [comment]
@luke- The wording has been updated in the commit https://github.com/humhub/questions/pull/16/commits/3cf9b1e4622f625c50c90fab29839d2d04de53dd.

**Pull request merged**
